site_name: discord-lfg
nav:
  - Home: index.md
  - Installation: installation.md
  - Running the bot: running.md
  - Configuration:
    - config/introduction.md
    - Token Input: config/token.md
    - General Configuration: config/general-config.md
    - Command Configuration: config/command-config.md
  - Discord Users:
    - Creating groups in Discord: users/creating_groups.md
    - Joining groups in Discord: users/joining_groups.md
    - Reviewing history and stats: users/stats.md
  - Contributing: contributing.md
  - Changelog: CHANGELOG.md
  - Reference: []
theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/aptosaurinae/discord-lfg/
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
      style_plain_text: shell
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: "#"
      toc_depth: 3
hooks:
  - docs/static/hooks.py
plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: spacy
            show_bases: true
            filters:
              - "!^_"
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: false
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
watch:
  - src/discord_lfg
extra_css:
  - static/extras.css
extra:
  version:
    provider: mike