help = """Post any issues in https://discord.com/channels/1055487463734386739/1194741620441096332

`/lfg` is used to create a group for the dungeon. \
Choose desired dungeon > dungeon difficulty > timed/completed > your role > required roles.

`/lfgquick` is used to quickly create a group using a set of text autocompletes which allows direct text input.

`/lfghistory` is used to check up-to 10 of your latest groups. Previous teammates & passphrases can be found here.

`/lfgstats` is used to check total groups created, groups created in the last 24h, 7d, 30d \
& also the most popular dungeons for each key range.

Notes:
- A generated `listed_as` group name will be supplied for you. \
This contains a random three-word suffix to assist members in finding your group in-game. \
This is the name you should use for your in-game group.
- You can assign your own `listed_as` name during the creation process by typing `/lfg`, \
choosing the `<listed_as>` option and entering your desired group name. \
It is recommended to avoid putting the key difficulty number as part of this to avoid getting random signups.
- A *hidden* passphrase is generated when you create a group. \
This is only available to you and the other members that join. \
If you are a group member, you can get a reminder of this by clicking on the 🔑 button
- Group members can change roles by clicking on another role.
- Group members can leave the group by clicking on the ⚙️ button.
- The group creator can cancel the group by clicking on the ⚙️ button \
and then clicking on `Cancel Group` 2x.
- LFG times out after 30 mins if there are still available spots.
- Once a group is filled, the group will no longer be editable after roughly 2 mins."""
