alphabet_names = [
    "ant",
    "bee",
    "cat",
    "duck",
    "eel",
    "fox",
    "gnu",
    "hen",
    "ibex",
    "jay",
    "koi",
    "lynx",
    "mole",
    "newt",
    "owl",
    "pig",
    "rat",
    "seal",
    "toad",
    "vole",
    "wolf",
    "yak",
]