EDA = "Eco-Dome Al'dani"
ARAK = "Ara-Kara, City of Echoes"
DAWN = "The Dawnbreaker"
PSF = "Priory of the Sacred Flame"
FLOOD = "Operation: Floodgate"
HOA = "Halls of Atonement"
STRT = "Tazavesh: Streets of Wonder"
GMBT = "Tazavesh: So'leah's Gambit"